language: python
python:
    - "2.7"
install: pip install -r blog/requirements.txt
before_script:
    - psql -c 'create database blogful-test;' -U postgres
script:
    - PYTHONPATH=./blog python blog/tests/test_filter.py
    - PYTHONPATH=./blog python blog/tests/test_pagination.py
    - PYTHONPATH=./blog python blog/tests/test_views_acceptance.py
    - PYTHONPATH=./blog python blog/tests/test_views_integration.py

